---
# Variables listed here are applicable to all host groups
#
# Ansible connection settings
ansible_user: administrator
ansible_password: "Password1234!"
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
#
# vCenter connection settings
vcenter_hostname: "192.168.255.20"
vcenter_username: "administrator@vsphere.local"
vcenter_password: "Password1234!"
datacenter_name: "Datacenter"
cluster_name: "Cluster"
vcenter_folder: "Servers"
template_core: "Win2022_Core"
template_gui: "Win2022_Gui"
virtual_machine_datastore: "Datastore"
validate_cert: "false"
#
# Define Domain Settings
#
domain: "test.co.uk"
netbios_domain: "test"
middle_level_domain: "co"
end_level_domain: "uk"
domain_admin: "{{ ansible_user }}@{{ domain }}"
domain_admin_username: "{{ ansible_user }}"
domain_admin_password: "Password1234!"
domain_safemode_password: "Password1234!"
#
# Computer names
# primary_domain_controller: "testdc001"
secondary_domain_controller: "testdc002"
horizon_connection_server1: "testcas001"
horizon_connection_server2: "testcas002"
#
# FQDN Settings
fqdn_primary_domain_controller: "{{ primary_domain_controller }}.{{ domain }}"
fqdn_secondary_domain_controller: "{{ secondary_domain_controller }}.{{ domain }}"
fqdn_horizon_connection_server1: "{{ horizon_connection_server1 }}.{{ domain }}"
fqdn_horizon_connection_server2: "{{ horizon_connection_server2 }}.{{ domain }}"
#
# AD OU Settings
Service_Accounts: "Service Accounts"
Administrator: "Admins"
Users: "Staff"
Member_Servers: "Servers"