---  
- name: join domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ DC2 }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: Password1234!
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- name: install ad
  microsoft.ad.domain_controller:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: Password1234!
    safe_mode_password: 1234!Password
    database_path: D:\NTDS
    sysvol_path: D:\SYSVOL
    state: domain_controller
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
  when: ad.changed