---
# Configure the primary domain controller
- hosts: DC1
  gather_facts: False
  roles:
   - deploy_winsrv_core
   - DC1

# Configure the secondary domain controller
- hosts: DC2
  gather_facts: False
  roles:
   - deploy_winsrv_core
   - DC2

# Domain join and install Horizon Connection Server
- hosts: HCS1
  gather_facts: False
  roles:
   - deploy_winsrv_gui
   - HCS1
   