---
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - "{{ groups['pdc'][0] }}"

- name: Change the hostname
  ansible.windows.win_hostname:
    name: "{{ exchange_server }}"
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_ou_path: "ou=Exchange,ou=Servers, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required