---
# Domain Group Creation
#
# Should these be Domain Local or Domain Global Groups?
#
# Create Employees Group
- name: Create Employees Group
  ansible.windows.win_group:
    name: Employees
    description: Employee Group
    state: present

# Create SQL Server Local Administrator
- name: Create SQL Local Administrator Group
  ansible.windows.win_group:
    name: SQL_LocalAdmin
    description: SQL Server Local Administrator
    state: present

# Create SQL Server SysAdmin
- name: Create SQL SysAdmin Group
  ansible.windows.win_group:
    name: SysAdmin
    description: SQL Server SysAdmin
    state: present

# Create SQL DB_Creator
- name: Create SQL DB_Creator Group
  ansible.windows.win_group:
    name: DB_Creator
    description: SQL Server DB_Creator
    state: present

# Create SQL SecurityAdmin 
- name: Create SQL SecurityAdmin Group
  ansible.windows.win_group:
    name: SecurityAdmin
    description: SQL Server SecurityAdmin
    state: present

# Domain OU Creation
# Create OU for User locations
- name: Install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present

- name: Create OU for Staff
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Staff"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Staff OU"
    Ensure: present

- name: Create OU for Admin
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Administrator OU"
    Ensure: present

- name: Create OU for Service Accounts
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Service Accounts"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Service Accounts OU"
    Ensure: present

# Create OU for Server locations
- name: Create OU for Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Servers"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Servers OU"
    Ensure: present

- name: Create OU for Exchange Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Exchange"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Exchange Servers OU"
    Ensure: present

- name: Create OU for Sharepoint Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Sharepoint"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "SharePoint OU"
    Ensure: present

- name: Create OU for SQL Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "SQL"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Microsoft SQL Servers OU"
    Ensure: present

# Domain User and Service Account Creation
# Create multiple users for Domain and add to respective groups
- name: Create administrator Account
  community.windows.win_domain_user:
    name: bakerg_admin
    firstname: Garry
    surname: Baker
    password: Pa55word
    Ensure: present
    path: "ou={{ Administrator }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Employees
    - Domain Users
    - Domain Admins
    - Enterprise Admins
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create Employee account
  community.windows.win_domain_user:
    name: bakerg
    firstname: Garry
    surname: Baker
    password: Pa55word
    Ensure: present
    path: "ou={{ Users }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Employees
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

# Create SQL Server Farm Service Accounts
- name: Create SharePoint Farm Account
  community.windows.win_domain_user:
    name: sp_farm
    firstname: SharePoint Farm
    surname: Service Account
    password: Pa55word
    Description: SharePoint Farm Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - DB_Creator
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Admin Account
  community.windows.win_domain_user:
    name: sp_admin
    firstname: SharePoint Admin
    surname: Service Account
    password: Pa55word
    Description: SharePoint Admin Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SecurityAdmin
    - DB_Creator
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Pool Account
  community.windows.win_domain_user:
    name: sp_pool
    firstname: SharePoint Pool
    surname: Service Account
    password: Pa55word
    Description: SharePoint Pool Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Services Account
  community.windows.win_domain_user:
    name: sp_services
    firstname: SharePoint Services
    surname: Service Account
    password: Pa55word
    Description: SharePoint Services Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Crawl Account
  community.windows.win_domain_user:
    name: sp_crawl
    firstname: SharePoint Crawl
    surname: Service Account
    password: Pa55word
    Description: SharePoint Crawl Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Search Account
  community.windows.win_domain_user:
    name: sp_search
    firstname: SharePoint search
    surname: Service Account
    password: Pa55word
    Description: SharePoint search Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint My Site Pool Account
  community.windows.win_domain_user:
    name: sp_mysitepool
    firstname: SharePoint My Site Pool
    surname: Service Account
    password: Pa55word
    Description: SharePoint MySitePool Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint User Profile Sync Account
  community.windows.win_domain_user:
    name: sp_userprofilesync
    firstname: SharePoint User Profile Sync
    surname: Service Account
    password: Pa55word
    Description: SharePoint User Profile Sync Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    #- Needs additional permissions
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Workflow Manager Service Account
  community.windows.win_domain_user:
    name: wf_service
    firstname: SharePoint Workflow Manager
    surname: Service Account
    password: Pa55word
    Description: SharePoint Workflow Manager Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super User Account
  community.windows.win_domain_user:
    name: sp_portalsuperuser
    firstname: SharePoint Portal Super User
    surname: Service Account
    password: Pa55word
    Description: SharePoint Portal Super User
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super Reader Account
  community.windows.win_domain_user:
    name: sp_portalsuperreader
    firstname: SharePoint Portal Super Reader
    surname: Service Account
    password: Pa55word
    Description: SharePoint Super Reader
    password_never_expires: yes
    user_cannot_change_password: yes
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"