
- name: Create a virtual machine from a template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vcneter_folder }}"
    name: "{{ hostname }}"
    state: poweredon
    template: "{{ template_core }}"
    disk:
    - size_gb: 10
      type: thin
      datastore: "{{ virtual_machine_datastore }}"
    hardware:
      memory_mb: "{{ RAM }}"
      num_cpus: "{{ CPU }}"
      num_cpu_cores_per_socket: "{{ sockets }}"
      scsi: paravirtual
#      memory_reservation_lock: true
#      mem_limit: 8096
#      mem_reservation: 4096
#      cpu_shares_level: "high"
#      mem_shares_level: "high"
#      cpu_limit: 8096
#      cpu_reservation: 4096
      max_connections: 5
      hotadd_cpu: true
      hotremove_cpu: true
      hotadd_memory: false
      version: 12 # Hardware version of virtual machine
      boot_firmware: "efi"
    networks:
    - name: VM Network
#        vlan: "{{ vLan_ID }}"
        ip: "{{ IP4 }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        type: static
    customization:
      existing_vm: True
      dns_servers:
      - "{{ DNS1 }}"
      - "{{ DNS2 }}"
    wait_for_ip_address: true
  delegate_to: localhost
  register: deploy