---
#
# This enables Windows Active Directory features and configures the primary domain controller
#
- name: Create new Windows domain in a new forest with specific parameters
  win_domain:
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios_domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
    database_path: D:\NTDS
    sysvol_path: D:\SYSVOL
  register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: ad.changed