
- name: Create a virtual machine from a template
  community.vmware.vmware_guest:
    validate_certs: false
    annotation: "{{ VM_notes }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vcenter_folder }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ hostname }}"
    state: poweredon
    template: "{{ template_core }}"
    hardware:
      memory_mb: "{{ RAM }}"
      num_cpus: "{{ CPU }}"
      max_connections: 1
      hotadd_cpu: true
      hotremove_cpu: true
      hotadd_memory: false
      version: latest # Hardware version of virtual machine
      boot_firmware: "efi"
    networks:
      - name: VM Network
        ip: "{{ IP4 }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        type: static
    customization:
      existing_vm: true
      hwclockUTC: true
      orgname: " Company name"
      dns_servers:
      - "{{ DNS1 }}"
      - "{{ DNS2 }}"
      dns_suffix:
        - "{{ domain }}"
    wait_for_ip_address: true
  delegate_to: localhost
  register: deploy


#      vlan: "{{ vLan_ID }}"
#      memory_reservation_lock: true
#      mem_limit: 8096
#      mem_reservation: 4096
#      cpu_shares_level: "high"
#      mem_shares_level: "high"
#      cpu_limit: 8096
#      cpu_reservation: 4096