---
# A gMSA requires a KDS root key to be created. Once created you will need to wait
# 10 hours for replication to all domain controllers before setting up 
# any managed service accounts
#
- name: Create KDS root key if not present
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      $Ansible.Changed = $false
      if (-not (Get-KdsRootKey)) {
          Add-KdsRootKey -EffectiveImmediately
          $Ansible.Changed = $true
      }