---
# Variables listed here are applicable to the specific hosts
#
# Define Server name
#
DC1: testdc001
hostname: "{{ DC1 }}"
#
# Define Hardware configuration
#
CPU: 2     # 4 Core
RAM: 4096  # 4 GB
#
# Defien Networks settings
#
VM_notes: Primary Domain Controller
IP4: 192.168.255.50
netmask: 255.255.255.0
gateway: 192.168.255.2
DNS1: 192.168.255.50
DNS2: 192.168.225.11