---
- name: Create a virtual machine from a template
  community.vmware.vmware_guest:
    validate_certs: false
    annotation: "{{ VM_notes }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vcenter_folder }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ hostname }}"
    state: poweredon
    template: "{{ template_core }}"
    hardware:
      memory_mb: "{{ RAM }}"
      num_cpus: "{{ CPU }}"
      max_connections: 1
      hotadd_cpu: true
      hotremove_cpu: true
      hotadd_memory: false
      version: latest
      boot_firmware: "efi"
    networks:
      - name: VM Network
        ip: "{{ IP4 }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        type: static
    customization:
      existing_vm: true
      hwclockUTC: true
      timezone: 085
      orgname: Company name
      password: Password1234!
      dns_servers:
      - "{{ DNS1 }}"
      - "{{ DNS2 }}"
      dns_suffix:
        - "{{ domain }}"
    wait_for_ip_address: true
  delegate_to: localhost
  register: deploy