---
#
# Configure DNS reverse lookup zones
#
- name: Configure DNS reverse lookup zone
  ansible.windows.win_shell: |
    Add-DnsServerPrimaryZone -NetworkID “192.168.255.0/24” -ReplicationScope “Domain”