---
- name: join domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ HCS1 }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: Password1234!
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required